using AgentExperience.Abstractions;
using AgentExperience.Core.Verification;

namespace AgentExperience.Core.Reflections;

/// <summary>
/// Everything an <see cref="IExperienceReflector"/> needs to produce one <see cref="Reflection"/>:
/// a finished run, the evaluation of that run, and the caller-supplied identity and timestamp the
/// resulting <see cref="Reflection"/> carries. Identity and time are supplied by the caller (never
/// generated by a reflector) so the same request always yields the same content.
/// </summary>
/// <remarks>
/// <para>
/// <b>A request is always bound.</b> The constructor refuses an <see cref="Evaluation"/> whose
/// <see cref="VerificationResult.Basis"/> names a run other than <see cref="Run"/>, with a
/// <see cref="ReflectionBindingException"/>. <see cref="Run"/> and <see cref="Evaluation"/> are
/// get-only, so a <c>with</c> expression cannot re-pair them, and a
/// <see cref="VerificationResult"/> can only come from <see cref="VerificationAggregator.Aggregate"/>,
/// which stamps the run ID it was given. Every <see cref="IExperienceReflector"/>, the default one or
/// a host's, therefore only ever receives a run together with an evaluation computed under that run's
/// ID.
/// </para>
/// <para>
/// The binding is exactly as strong as the run ID. A caller that aggregates made-up evidence under a
/// run's ID, or re-stamps another run with <c>run with { RunId = ... }</c> (and no outcome of its own
/// to contradict the evaluation), is stating a pairing the library cannot check, the same trust as
/// every other host-supplied identifier.
/// </para>
/// <para>
/// <see cref="EnsureMatches"/> is the output side of the same binding: it checks that a
/// <see cref="Reflection"/> says what this request asked for.
/// <see cref="Finalization.ExperienceFinalizationService"/> applies it to every reflection a
/// reflector returns; a host that calls a reflector directly can apply it too.
/// </para>
/// </remarks>
/// <param name="Run">The finished (<see cref="ExperienceRun.ExecutionStatus"/> set), sanitized run to reflect on. If its own <see cref="ExperienceRun.Outcome"/> is set, its <see cref="Outcome.Status"/> must match <see cref="Evaluation"/>'s.</param>
/// <param name="Evaluation">The verification result for <see cref="Run"/> -- the only source of verdict and evidence a reflector may use. Its <see cref="VerificationResult.Basis"/> must name <see cref="Run"/>'s <see cref="ExperienceRun.RunId"/>.</param>
/// <param name="ReflectionId">The identifier the produced <see cref="Reflection"/> carries.</param>
/// <param name="CreatedAt">The timestamp the produced <see cref="Reflection"/> carries.</param>
/// <exception cref="ArgumentNullException"><paramref name="Run"/> or <paramref name="Evaluation"/> is <see langword="null"/>.</exception>
/// <exception cref="ReflectionBindingException"><paramref name="Evaluation"/> was computed for a different run, or <paramref name="Run"/>'s own outcome status disagrees with it.</exception>
public sealed record ReflectionRequest(
    ExperienceRun Run,
    VerificationResult Evaluation,
    Guid ReflectionId,
    DateTimeOffset CreatedAt)
{
    /// <summary>The finished run to reflect on.</summary>
    public ExperienceRun Run { get; } = Run ?? throw new ArgumentNullException(nameof(Run), "The reflection request's Run must not be null.");

    /// <summary>The verification result computed for <see cref="Run"/>; never one computed for another run.</summary>
    public VerificationResult Evaluation { get; } = EnsureBound(Run, Evaluation);

    /// <summary>
    /// Checks that <paramref name="reflection"/> is what this request asked for: its
    /// <see cref="Reflection.ReflectionId"/>, <see cref="Reflection.CreatedAt"/> and
    /// <see cref="Reflection.ExperienceRunId"/> are this request's, and its
    /// <see cref="Reflection.VerificationStatus"/>, <see cref="Reflection.CompletionScore"/>,
    /// <see cref="Reflection.VerificationRuleVersion"/> and <see cref="Reflection.EvidenceIds"/> are
    /// <see cref="Evaluation"/>'s (the evidence IDs distinct, in the order the evidence was produced).
    /// These are items 1 and 2 of <see cref="IExperienceReflector"/>'s structured-content contract.
    /// </summary>
    /// <param name="reflection">A reflection some <see cref="IExperienceReflector"/> returned for this request.</param>
    /// <exception cref="ArgumentNullException"><paramref name="reflection"/> is <see langword="null"/>.</exception>
    /// <exception cref="ReflectionBindingException">The reflection does not match this request; the message names the first field that differs and carries no captured text.</exception>
    public void EnsureMatches(Reflection reflection)
    {
        ArgumentNullException.ThrowIfNull(reflection);

        var outcome = Evaluation.Outcome;
        var mismatch =
            reflection.ReflectionId != ReflectionId ? nameof(Reflection.ReflectionId)
            : reflection.ExperienceRunId != Run.RunId ? nameof(Reflection.ExperienceRunId)
            : reflection.CreatedAt != CreatedAt ? nameof(Reflection.CreatedAt)
            : reflection.VerificationStatus != outcome.Status ? nameof(Reflection.VerificationStatus)
            : !reflection.CompletionScore.Equals(Evaluation.CompletionScore) ? nameof(Reflection.CompletionScore)
            : !string.Equals(reflection.VerificationRuleVersion, Evaluation.RuleVersion, StringComparison.Ordinal) ? nameof(Reflection.VerificationRuleVersion)
            : reflection.EvidenceIds is null || !reflection.EvidenceIds.SequenceEqual(DistinctInProducedOrder(outcome.Evidence)) ? nameof(Reflection.EvidenceIds)
            : null;

        if (mismatch is not null)
        {
            throw new ReflectionBindingException(
                $"The reflection's {mismatch} does not match the reflection request for run {Run.RunId:D}; a reflection must carry the request's identity and copy its evaluation exactly.",
                nameof(reflection),
                Run.RunId,
                mismatch);
        }
    }

    /// <summary>The evaluation's distinct evidence IDs, first occurrence first (contract item 2).</summary>
    private static List<Guid> DistinctInProducedOrder(IReadOnlyList<Evidence> evidence)
    {
        var seen = new HashSet<Guid>();
        var ids = new List<Guid>(evidence.Count);
        foreach (var item in evidence)
        {
            if (seen.Add(item.EvidenceId))
            {
                ids.Add(item.EvidenceId);
            }
        }

        return ids;
    }

    /// <summary>
    /// Returns <paramref name="evaluation"/> when it was computed for <paramref name="run"/> (its
    /// basis names the run's ID) and, when the run carries an outcome of its own, that outcome's
    /// status agrees with the evaluation's; throws otherwise. Shared by the constructor and <see cref="DefaultExperienceReflector"/>'s own
    /// validation.
    /// </summary>
    /// <param name="run">The run the evaluation is to be paired with.</param>
    /// <param name="evaluation">The evaluation.</param>
    /// <returns><paramref name="evaluation"/>.</returns>
    internal static VerificationResult EnsureBound(ExperienceRun? run, VerificationResult? evaluation)
    {
        if (run is null)
        {
            throw new ArgumentNullException(nameof(Run), "The reflection request's Run must not be null.");
        }

        if (evaluation is null)
        {
            throw new ArgumentNullException(nameof(Evaluation), "The reflection request's Evaluation must not be null.");
        }

        if (evaluation.Basis.RunId != run.RunId)
        {
            throw new ReflectionBindingException(
                $"The evaluation was computed for run {evaluation.Basis.RunId:D}, not for run {run.RunId:D}; a reflection can only be built from the evaluation of the run it reflects on.",
                nameof(Evaluation),
                run.RunId,
                nameof(VerificationBasis.RunId));
        }

        // A run that already says how it was judged must say the same thing as the evaluation it is
        // paired with. This also catches a run re-stamped with another run's ID whose own outcome
        // disagrees; one with no outcome of its own is covered by the run-ID check alone.
        if (run.Outcome is not null && run.Outcome.Status != evaluation.Outcome.Status)
        {
            throw new ReflectionBindingException(
                $"The run's own Outcome.Status ({run.Outcome.Status}) does not match the evaluation's Outcome.Status ({evaluation.Outcome.Status}) for run {run.RunId:D}.",
                nameof(Evaluation),
                run.RunId,
                "Outcome.Status");
        }

        return evaluation;
    }
}
