using AgentExperience.Abstractions;
using AgentExperience.Core.Verification;

namespace AgentExperience.Core.Reflections;

/// <summary>
/// Everything an <see cref="IExperienceReflector"/> needs to produce one <see cref="Reflection"/>:
/// a finished run, the evaluation of that run, and the caller-supplied identity and timestamp the
/// resulting <see cref="Reflection"/> carries. Identity and time are supplied by the caller (never
/// generated by a reflector) so the same request always yields the same content.
/// </summary>
/// <param name="Run">The finished (<see cref="ExperienceRun.ExecutionStatus"/> set), sanitized run to reflect on. If its own <see cref="ExperienceRun.Outcome"/> is set, its <see cref="Outcome.Status"/> must match <see cref="Evaluation"/>'s.</param>
/// <param name="Evaluation">The verification result for <see cref="Run"/> -- the only source of verdict and evidence a reflector may use.</param>
/// <param name="ReflectionId">The identifier the produced <see cref="Reflection"/> carries.</param>
/// <param name="CreatedAt">The timestamp the produced <see cref="Reflection"/> carries.</param>
public sealed record ReflectionRequest(
    ExperienceRun Run,
    VerificationResult Evaluation,
    Guid ReflectionId,
    DateTimeOffset CreatedAt);
